export function fetch(config = {}){
    const { url } = config
    if(url === '/list'){
        return new Promise((resolve) => {
            setTimeout(() => {
                resolve({
                    data: {
                        data: {
                            "pageNum": 1,
                            "pageSize": 15,
                            "rows": [
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 57,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Tenant_Type",
                                    "dicName": "租户类型",
                                    "parentId": 0,
                                    "dicValue": "Tenant_Type",
                                    "sort": 1,
                                    "pkeyPath": "Tenant_Type",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "租户类型",
                                    "createUser": "01422248",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 62,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Sharing_Center_Type",
                                    "dicName": "共享中心类型",
                                    "parentId": 0,
                                    "dicValue": "Sharing_Center_Type",
                                    "sort": 2,
                                    "pkeyPath": "Sharing_Center_Type",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01422248",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 65,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Sharing_Center_Attribute",
                                    "dicName": "共享中心属性",
                                    "parentId": 0,
                                    "dicValue": "Sharing_Center_Attribute",
                                    "sort": 3,
                                    "pkeyPath": "Sharing_Center_Attribute",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01422248",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 69,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "System_Source",
                                    "dicName": "系统来源",
                                    "parentId": 0,
                                    "dicValue": "System_Source",
                                    "sort": 4,
                                    "pkeyPath": "System_Source",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01422248",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 73,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Md_Type",
                                    "dicName": "主数据类型",
                                    "parentId": 0,
                                    "dicValue": "Md_Type",
                                    "sort": 5,
                                    "pkeyPath": "Md_Type",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01422248",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 88,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Operator_Type",
                                    "dicName": "操作符",
                                    "parentId": 0,
                                    "dicValue": "Operator_Type",
                                    "sort": 6,
                                    "pkeyPath": "Operator_Type",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 95,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Logical_Symbol",
                                    "dicName": "逻辑关系",
                                    "parentId": 0,
                                    "dicValue": "Logical_Symbol",
                                    "sort": 7,
                                    "pkeyPath": "Logical_Symbol",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 99,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Sensitive_Data_Setting",
                                    "dicName": "敏感设置",
                                    "parentId": 0,
                                    "dicValue": "Sensitive_Data_Setting",
                                    "sort": 8,
                                    "pkeyPath": "Sensitive_Data_Setting",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 103,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Business_Segment",
                                    "dicName": "业务板块",
                                    "parentId": 0,
                                    "dicValue": "Business_Segment",
                                    "sort": 9,
                                    "pkeyPath": "Business_Segment",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:57",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:57",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 117,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Area_Org",
                                    "dicName": "区部",
                                    "parentId": 0,
                                    "dicValue": "Area_Org",
                                    "sort": 10,
                                    "pkeyPath": "Area_Org",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:58",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:58",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 48,
                                    "tenantId": 452,
                                    "tenantName": "顺丰财务共享中",
                                    "dicKey": "difficulty_level",
                                    "dicName": "难易程度",
                                    "parentId": 0,
                                    "dicValue": "difficultyLevel",
                                    "sort": 12,
                                    "pkeyPath": "difficulty_level",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01419172",
                                    "createTime": "2023-05-11 08:31:56",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:56",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 39,
                                    "tenantId": 452,
                                    "tenantName": "顺丰财务共享中",
                                    "dicKey": "priority_level",
                                    "dicName": "优先级",
                                    "parentId": 0,
                                    "dicValue": "priorityLevel",
                                    "sort": 13,
                                    "pkeyPath": "priority_level",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01419172",
                                    "createTime": "2023-05-11 08:31:56",
                                    "updateUser": "166046",
                                    "updateTime": "2023-05-11 08:31:56",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 462,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Log_Operate_Type",
                                    "dicName": "日志操作类型",
                                    "parentId": 0,
                                    "dicValue": "logOperateType",
                                    "sort": 13,
                                    "pkeyPath": "Log_Operate_Type",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "01419172",
                                    "createTime": "2023-05-26 03:38:00",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-26 03:38:00",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 149,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Industry",
                                    "dicName": "所属行业",
                                    "parentId": 0,
                                    "dicValue": "Industry",
                                    "sort": 14,
                                    "pkeyPath": "Industry",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:58",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:58",
                                    "params": {}
                                },
                                {
                                    "tenantCode": "",
                                    "userName": null,
                                    "pageNum": 1,
                                    "pageSize": 10,
                                    "id": 167,
                                    "tenantId": 452,
                                    "tenantName": "顺丰大网",
                                    "dicKey": "Tax_Type",
                                    "dicName": "纳税类型",
                                    "parentId": 0,
                                    "dicValue": "Tax_Type",
                                    "sort": 15,
                                    "pkeyPath": "Tax_Type",
                                    "status": 1,
                                    "isChild": 1,
                                    "remark": "",
                                    "createUser": "166046",
                                    "createTime": "2023-05-11 08:31:59",
                                    "updateUser": "SYSTEM",
                                    "updateTime": "2023-05-11 08:31:59",
                                    "params": {}
                                }
                            ],
                            "totalSize": 42,
                            "totalPage": 3
                        },
                        totalPage: 3,
                        totalSize: 4,
                        pageNum: 1,
                        pageSize: 15
                    }
                })
            }, 2000)
        })
    }
}